#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 

# DRACULA THEME COLOR BORDER #
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"


bspc config border_width         1
bspc config window_gap           10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a discord desktop='^4'
bspc rule -a notion-app-enhanced desktop='^6'
bspc rule -a scratchpad sticky=on state=floating rectangle=1720x880+100+100
bspc rule -a feh state=floating 

# Auto start
picom -b &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &
playerctl daemon &
xidlehook --not-when-audio --not-when-fullscreen --timer 600 '/usr/local/bin/slock' '' &
xidlehook --not-when-fullscreen --timer 900 '/usr/local/bin/slock' '' &
redshift &
sxhkd -m 1
